title: Veronica Valeros
email: vero.valeros@gmail.com
description: I'm verovaleros, a hacker, researcher, and artist. I work at the Stratosphere Cybersecurity Research Laboratory at the AIC, FEL, Czech Technical University in Prague.
logo: assets/veronica-valeros.jpg
theme: jekyll-theme-minimal
url: https://verovaleros.github.io
show_downloads: true
blog_url: blog
github:
  owner_name: verovaleros
  repo_url: https://github.com/verovaleros
  linkedin_url: https://www.linkedin.com/in/veronicavalerossaracho/
author: Veronica Valeros
twitter_username: verovaleros
github_username:  verovaleros
plugins:
  - jekyll-feed
